my:
  app:
    name: containertracer
    version: 1.0

#spring:
#  data:
#    web:
#      pageable:
#        default-page-size: 1
#        max-page-size: 100
#        page-parameter: pageNumber
#        size-parameter: pageSize
#        one-indexed-parameters: false
